// Generated by github.com/steida/coffee2closure 0.1.3
goog.provide('App');

/**
  @param {app.Routes} routes
  @param {este.Router} router
  @param {app.todos.react.App} reactApp
  @param {Element} element
  @param {app.todos.Store} store
  @constructor
 */
var App = function(routes, router, reactApp, element, store) {
  var syncUI;
  this.reactApp = reactApp;
  this.element = element;
  syncUI = function() {
    return React.renderComponent(reactApp.component(), element);
  };
  routes.addToEste(router, function(route, params) {
    routes.setActive(route, params);
    return syncUI();
  });
  router.start();
  store.listen('change', syncUI);
}