// Generated by github.com/steida/coffee2closure 0.1.3
goog.provide('App');

/**
  @param {este.Router} router
  @param {app.Routes} routes
  @param {app.todos.react.App} reactApp
  @param {Element} element
  @constructor
 */
var App = function(router, routes, reactApp, element) {
  this.reactApp = reactApp;
  this.element = element;
  routes.addToEste(router);
  routes.listen(este.Routes.EventType.CHANGE, this.syncUi.bind(this));
  router.start();
}

/**
  Sync UI with app model.
 */
App.prototype.syncUi = function() {
  if (!this.component) {
    this.component = React.renderComponent(this.reactApp.create(), this.element);
    return;
  }
  return this.component.forceUpdate();
};