// Generated by github.com/steida/coffee2closure 0.1.3
goog.provide('app.Routes');
goog.require('este.Routes');

/**
  @constructor
  @extends {este.Routes}
 */
app.Routes = function() {
  this.allTodos = this.route('/');
  this.activeTodos = this.route('/active');
  this.completedTodos = this.route('/completed');
}
goog.inherits(app.Routes, este.Routes);